// Package transcription integrates the local OpenAI Whisper Python package.
package transcription

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ai-video-dubber/ai-video-dubber-go/internal/executil"
	"github.com/ai-video-dubber/ai-video-dubber-go/internal/srt"
)

const whisperScript = `
import json
import sys

import whisper

input_path, model_name, language, output_json = sys.argv[1:5]
model = whisper.load_model(model_name)
result = model.transcribe(
    input_path,
    language=language,
    task="transcribe",
    verbose=False,
    word_timestamps=True,
    fp16=False,
)

def make_safe(value):
    if isinstance(value, dict):
        return {str(k): make_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [make_safe(v) for v in value]
    if hasattr(value, "item"):
        try:
            return value.item()
        except Exception:
            pass
    return value

with open(output_json, "w", encoding="utf-8") as handle:
    json.dump(make_safe(result), handle, ensure_ascii=False, indent=2)
`

type whisperResult struct {
	Text     string           `json:"text"`
	Segments []whisperSegment `json:"segments"`
}

type whisperSegment struct {
	Start float64 `json:"start"`
	End   float64 `json:"end"`
	Text  string  `json:"text"`
}

// OutputPaths describes the four artifacts generated by the reference project.
type OutputPaths struct {
	SRT      string
	Segments string
	JSON     string
	Text     string
}

// Run transcribes audio locally and writes SRT, segments, JSON, and plain text.
func Run(
	ctx context.Context,
	runner executil.Runner,
	pythonExe, inputPath, model, sourceLanguage string,
	outputs OutputPaths,
) error {
	if strings.TrimSpace(model) == "" {
		model = "large-v3"
	}
	if strings.TrimSpace(sourceLanguage) == "" {
		sourceLanguage = "en"
	}
	if err := os.MkdirAll(filepath.Dir(outputs.JSON), 0o755); err != nil {
		return fmt.Errorf("create transcript directory: %w", err)
	}
	tempJSON, err := os.CreateTemp(filepath.Dir(outputs.JSON), ".whisper-*.json")
	if err != nil {
		return fmt.Errorf("create temporary Whisper JSON: %w", err)
	}
	tempPath := tempJSON.Name()
	if err := tempJSON.Close(); err != nil {
		return fmt.Errorf("close temporary Whisper JSON: %w", err)
	}
	defer os.Remove(tempPath)

	args := []string{"-c", whisperScript, inputPath, model, sourceLanguage, tempPath}
	if err := runner.Run(ctx, pythonExe, args, executil.Options{}); err != nil {
		return fmt.Errorf("Whisper transcription: %w", err)
	}

	data, err := os.ReadFile(tempPath)
	if err != nil {
		return fmt.Errorf("read Whisper result: %w", err)
	}
	var result whisperResult
	if err := json.Unmarshal(data, &result); err != nil {
		return fmt.Errorf("decode Whisper result: %w", err)
	}
	cues := make([]srt.Cue, 0, len(result.Segments))
	for _, segment := range result.Segments {
		text := strings.TrimSpace(segment.Text)
		if text == "" || segment.End <= segment.Start {
			continue
		}
		cues = append(cues, srt.Cue{
			Index: len(cues) + 1,
			Start: time.Duration(segment.Start * float64(time.Second)),
			End:   time.Duration(segment.End * float64(time.Second)),
			Text:  text,
		})
	}
	if len(cues) == 0 {
		return fmt.Errorf("Whisper returned no subtitle segments")
	}

	if err := srt.WriteFile(outputs.SRT, cues); err != nil {
		return err
	}
	if err := srt.WriteSegmentsFile(outputs.Segments, cues); err != nil {
		return err
	}
	if err := srt.WritePlainText(outputs.Text, cues); err != nil {
		return err
	}
	if err := os.Chmod(tempPath, 0o644); err != nil {
		return fmt.Errorf("set Whisper JSON permissions: %w", err)
	}
	if err := atomicReplace(tempPath, outputs.JSON); err != nil {
		return fmt.Errorf("save Whisper JSON: %w", err)
	}
	return nil
}

func atomicReplace(source, destination string) error {
	if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
		return err
	}
	// os.Rename replaces atomically on Unix. Windows requires removing an
	// existing destination first, so use a conservative cross-platform fallback.
	if err := os.Rename(source, destination); err == nil {
		return nil
	} else if _, statErr := os.Stat(destination); statErr != nil {
		return err
	}
	if err := os.Remove(destination); err != nil && !os.IsNotExist(err) {
		return err
	}
	return os.Rename(source, destination)
}
